### PR TITLE
Feature/optimizations

### PR DESCRIPTION
**Pull request by darkmavis1980**
Changes:
- Improved how lodash is imported
- Removed lodash were unnecessary
- Removed legacy dependencies
- Removed `btoa` package as it was imported but never used
- Replaced `qs` with more appropriate `URLSearchParams`

### CODE REVIEW

**Comment by ksvirkou-hubspot** [comment]
We cannot change codegen (this SDK is automatically generated)

**Comment by darkmavis1980** [comment]
@ksvirkou-hubspot Ok, but be aware that you are using unmaintained dependencies that shouldn't really be used anymore

**Comment by ksvirkou-hubspot** [comment]
I'll try optimize code generator
if it it possible

**Comment by ksvirkou-hubspot** [comment]
You can create issue and I'll answer

**Pull request closed without merging**
