### PR TITLE
Memory usage

### PR DESCRIPTION
**Pull request by ksvirkou-hubspot**
Memory usage was checked with `process.memoryUsage()`
main param is heapUsed (32.24 MB => 10 MB)
Before 
```
rss 94.17 MB
heapTotal 55.28 MB
heapUsed 32.24 MB
external 1.21 MB
arrayBuffers 0.6 MB
```

After
```
rss 48.44 MB
heapTotal 17.3 MB
heapUsed 10 MB
external 0.63 MB
arrayBuffers 0.03 MB

### CODE REVIEW

**Review by plaurynovich-hubspot — APPROVED** [review]

**Review by atanasiuk-hubspot — APPROVED** [review]

**Comment by batflarrow** [comment]
@ksvirkou-hubspot when is this pr going to be released? I have this package in my project and my test cases keep failing due to BUILD_TIMEOUT because of the loading time of this client. I could increase the build_timeout but is there anything I can do from my end to avoid this?

**Comment by ksvirkou-hubspot** [comment]
@batflarrow 
I've just published it
Could you check [the latest version](https://github.com/HubSpot/hubspot-api-nodejs/releases/tag/8.0.0)?

**Comment by batflarrow** [comment]
> @batflarrow I've just published it Could you check [the latest version](https://github.com/HubSpot/hubspot-api-nodejs/releases/tag/8.0.0)?

Going through the release I think this was reverted, will upgrading to latest version still help?

**Comment by ksvirkou-hubspot** [comment]
https://github.com/HubSpot/hubspot-api-nodejs/pull/267 
will be released as soon as possible

**Pull request merged**
