### PR TITLE
Regenerate all associations APIs

### PR DESCRIPTION
**Pull request by ksvirkou-hubspot**
https://github.com/HubSpot/hubspot-api-nodejs/issues/273

### CODE REVIEW

**Review by atanasiuk-hubspot — APPROVED** [review]

**Comment by oleg-vysotsky** [comment]
@atanasiuk-hubspot current associations APIs is broken for me? Look like that should fix it, when it will be released?

**Comment by ksvirkou-hubspot** [comment]
We are going to release it on Monday

**Comment by ksvirkou-hubspot** [comment]
> @ksvirkou-hubspot @atanasiuk-hubspot current associations APIs is broken for me. Look like that should fix it, when it will be released?

I ve published it

**Comment by oleg-vysotsky** [comment]
@ksvirkou-hubspot great, thank you! Then I'll try to upgrade.

**Pull request merged**
